formatter: markdown table

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sections:
  show:
    - inputs
    - outputs

sort:
  enabled: true
  by: required

settings:
  anchor: false
  lockfile: false
  # Nest generated headings under each README's existing section heading
  indent: 3
